apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-site
  name: my-site
  namespace: my-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-site
  strategy: {}
  template:
    metadata:
      labels:
        app: my-site
    spec:
      containers:
      - image: ghcr.io/forthexp/about-me@sha256:450d00a12c8429475e8eb775b3b375a84bf92ba969e93adade8605cacf361ab4
        name: about-me
      imagePullSecrets:
      - name: ghcr-secret
